### ISSUE TITLE
support sceptre plugins

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/github-ci-action#1]
I want to use the [sceptre ssm resolver](https://pypi.org/project/sceptre-ssm-resolver)  which isn't a core resolver.  Typically I would need to pip install that into my environment to be able to use it with sceptre.  I'm hoping that i'm wrong but there doesn't seem to be a way for me to add sceptre hooks & resolvers to this GH action.  Also hoping that there's a workaround if I am indeed correct?

**Comment by BrunoGrandePhD** [comment]
Resolved in #3.
